### ISSUE TITLE
ModuleNotFoundError: No module named 'IPy'

### ISSUE THREAD

**Issue by agoodshort** [jinxo13/HuaweiB525Router#5]
Hi, first of all thanks for the hard-work on this. I have been looking for a solution for the last two days to get around the DNS of my B525.
I am fairly new with python and I can't get around the below. I am not sure if it is because I am not experienced enough, or there is actually an issue. Can you help?
```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import huawei_lte.router as lte
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router-master/huawei_lte/router.py", line 12, in <module>
    import huawei_lte.xmlobjects as xmlobjects
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router-master/huawei_lte/xmlobjects.py", line 4, in <module>
    import huawei_lte.utils as utils
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router-master/huawei_lte/utils.py", line 1, in <module>
    from IPy import IP
ModuleNotFoundError: No module named 'IPy'
```
FYI:
- I am on a mac
- Used the build in python 2.7.16
- ran `pip install requests`
- ran `python setup.py install`
- ran `python test.py`
- Installed python via brew
- python 3.7.6
- ran `pip3 install requests`
- ran `python3 setup.py install`
- ran `python3 test.py`
- this is my test.py
```
import huawei_lte.router as lte
import huawei_lte.xmlobjects as xmlobjects
from huawei_lte.errors import RouterError

#Connect to the router
router = lte.B525Router('192.168.8.1')
router.login(username='admin', password='xxx') #Throws RouterError on a login error

#Get a list of what API calls appear to be are supported (GET requests only)
response = router.features
```

**Comment by jinxo13** [comment]
Hi goodshort,

try running: pip3 install IPy
Looks like I missed a dependency, I've made an update to fix this.

Cheers,
Hamish

**Comment by agoodshort** [comment]
Hi Hamish,
Thanks a lot for the quick reply!
I downloaded the fix, ran `pip3 install IPy` and got the below:
```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import huawei_lte.router as lte
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/router.py", line 12, in <module>
    import huawei_lte.xmlobjects as xmlobjects
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/xmlobjects.py", line 5, in <module>
    from huawei_lte.errors import RouterError
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/errors.py", line 1, in <module>
    import xmlobjects as xmlobjects
ModuleNotFoundError: No module named 'xmlobjects'
```
So I ran `pip3 install xmlobjects`
And ran into this:
```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import huawei_lte.router as lte
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/router.py", line 12, in <module>
    import huawei_lte.xmlobjects as xmlobjects
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/xmlobjects.py", line 5, in <module>
    from huawei_lte.errors import RouterError
  File "/Users/adrimac/Documents/Smart-Home/HuaweiB525Router/huawei_lte/errors.py", line 1, in <module>
    import xmlobjects as xmlobjects
  File "/usr/local/lib/python3.7/site-packages/xmlobjects/__init__.py", line 33
    raise TypeError, 'Not xmlobjects.element_type'
                   ^
SyntaxError: invalid syntax
```
Is my test.py file wrong?

Cheers,
Adrien

**Comment by ghost** [comment]
xmlobjects only works in python 2

**Comment by jinxo13** [comment]
Thanks @nickberry17  - yep the code is Python 2 only - no Python 3 support.

@goodshort - on your test.py code the import should use:
import huawei_lte.xmlobjects as xmlobjects

As per the example on the readme page.
Hopefully that all helps - good luck!

I'm closing as the IPy issue is solved - but feel free to raise another issue if you still are having difficulty.

Cheers,
Hamish
